# -*- coding: utf-8 -*-
"""meu primeiro algoritimo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ReB9hmtq5fATzzLRBjLVljpIH3qA4Bu9
"""

nome_usuario = input("por favor, insira seu nome:")
print(f"olá, {nome_usuario}!bem vindo ao nosso sistema.")
input ("por favor, insira 2 valores:")
input ("qual operação o usúario deseja fazer: soma ou subtração")
input ("escolha dois números")
número_usuario = int(input("insira o resultado"))
resultado_soma = 50
subtração = 20
if (resultado_soma >= 50 and subtração > 20) or resultado_soma > 20:
  print("CERTO")

